pipeline {
    agent any

    environment {
        DOTNET_VERSION = "8.0.x"
        DOTNET_HOME = "/usr/local/share/dotnet"
        PATH = "/usr/local/share/dotnet:$PATH"
    }

    triggers {
        //Daily run at 02:00AM
        cron('H 2 * * *')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'feature/module9-cicd', url: 'https://github.com/BuchRepository/com.epam.rp.git'
            }
        }

        stage('Setup .NET') {
            steps {
                echo "Checking .NET SDK installation..."
                sh '$DOTNET_HOME/dotnet --version'
                sh '$DOTNET_HOME/dotnet --info'
            }
        }

        stage('Inject credentials') {
            steps {
                withCredentials([
                    string(credentialsId: 'LOGIN', variable: 'LOGIN'),
                    string(credentialsId: 'PASSWORD', variable: 'PASSWORD'),
                    string(credentialsId: 'API_TOKEN', variable: 'API_TOKEN'),
                    string(credentialsId: 'SONAR_QUBE_TOKEN', variable: 'SONAR_QUBE_TOKEN'),
                    string(credentialsId: 'SLACK_WEBHOOK_URL', variable: 'SLACK_WEBHOOK_URL')
                ]) {
                    echo "Environment variables injected."
                    sh '''
                        echo "LOGIN=$LOGIN"
                        echo "PASSWORD=[HIDDEN]"
                        echo "API_TOKEN=[HIDDEN]"
                        echo "SONAR_QUBE_TOKEN=[HIDDEN]"
                        echo "SLACK_WEBHOOK_URL=[HIDDEN]"
                    '''
                }
            }
        }

        stage('Restore dependencies') {
            steps {
                echo "Restoring dependencies..."
                sh '$DOTNET_HOME/dotnet restore com.epam.rp.sln'
            }
        }

        stage('Build solution') {
            steps {
                echo "Building project..."
                sh '$DOTNET_HOME/dotnet build com.epam.rp.sln --configuration Release --no-restore'
            }
        }

        stage('Check ReportPortal config') {
            steps {
                echo "Checking ReportPortal.config.json..."
                sh 'find . -name "ReportPortal.config.json"'
            }
        }

        stage('SonarQube Analysis') {
            environment {
                PATH = "/Users/sergiibuchkivskyi/.dotnet/tools:$PATH"
            }
            steps {
                withCredentials([string(credentialsId: 'SONAR_QUBE_TOKEN', variable: 'SONAR_QUBE_TOKEN')]) {
                    sh '''
                        dotnet-sonarscanner begin /o:"buchrepository" /k:"BuchRepository_com.epam.rp" /d:sonar.login=$SONAR_QUBE_TOKEN
                        $DOTNET_HOME/dotnet build
                        dotnet-sonarscanner end /d:sonar.login=$SONAR_QUBE_TOKEN
                    '''
                }
            }
        }

        stage('Run API tests') {
            environment {
                LOGIN = credentials('LOGIN')
                PASSWORD = credentials('PASSWORD')
                API_TOKEN = credentials('API_TOKEN')
                SLACK_WEBHOOK_URL = credentials('SLACK_WEBHOOK_URL')
            }
            steps {
                withCredentials([string(credentialsId: 'API_TOKEN', variable: 'RP_UUID')]) {
                    sh '''
                        echo "Running API tests with ReportPortal integration..."

                        sed -i '' "s/\\"uuid\\": \\"\\"/\\"uuid\\": \\"$RP_UUID\\"/" com.epam.rp.api/ReportPortal.config.json
                        grep '"uuid"' com.epam.rp.api/ReportPortal.config.json | sed 's/".*"/"***"/'

                        echo "ReportPortal config updated for API tests"
                        $DOTNET_HOME/dotnet test com.epam.rp.api/com.epam.rp.api.csproj \
                            --configuration Release \
                            --logger:"console;verbosity=detailed"
                    '''
                }
            }
        }

        stage('Upload API Report') {
            steps {
                echo 'Uploading API report as artifact...'
                archiveArtifacts artifacts: 'com.epam.rp.api/bin/Release/net8.0/index.html', fingerprint: true
            }
        }

        stage('Run UI tests on Sauce Labs') {
            steps {
                withCredentials([
                    string(credentialsId: 'SAUCE_USERNAME', variable: 'SAUCE_USERNAME'),
                    string(credentialsId: 'SAUCE_ACCESS_KEY', variable: 'SAUCE_ACCESS_KEY'),
                    string(credentialsId: 'SLACK_WEBHOOK_URL', variable: 'SLACK_WEBHOOK_URL')
                ]) {
                    sh '''
                        echo "Running UI tests on Sauce Labs..."
                        echo "Using Sauce username: $SAUCE_USERNAME"

                        export SAUCE_USERNAME=$SAUCE_USERNAME
                        export SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY
                        export USE_SAUCELABS=true
                        export RUN_REMOTE=true
                        export SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL

                        $DOTNET_HOME/dotnet test com.epam.rp.ui/com.epam.rp.ui.csproj \
                            --configuration Release \
                            --logger:"console;verbosity=detailed"
                    '''
                }
            }
        }

        stage('Run UI tests') {
            environment {
                LOGIN = credentials('LOGIN')
                PASSWORD = credentials('PASSWORD')
                API_TOKEN = credentials('API_TOKEN')
                SLACK_WEBHOOK_URL = credentials('SLACK_WEBHOOK_URL')
            }
            steps {
                withCredentials([string(credentialsId: 'API_TOKEN', variable: 'RP_UUID')]) {
                    sh '''
                        echo "Running UI tests..."

                        sed -i '' "s/\\"uuid\\": \\"\\"/\\"uuid\\": \\"$RP_UUID\\"/" com.epam.rp.ui/ReportPortal.config.json

                        echo "ReportPortal config updated for UI tests"
                        $DOTNET_HOME/dotnet test com.epam.rp.ui/com.epam.rp.ui.csproj \
                            --configuration Release \
                            --logger:"console;verbosity=detailed" \
                            --logger:"reportportal;config=$(pwd)/com.epam.rp.ui/ReportPortal.config.json"
                    '''
                }
            }
        }

	stage('Upload UI Report') {
            steps {
                archiveArtifacts artifacts: 'com.epam.rp.ui/bin/Release/net8.0/index.html', fingerprint: true
            }
        }
    }

    post {
        success {
            echo 'All tests passed successfully!'
        }
        failure {
            echo 'Some tests failed.'
        }
        always {
            echo 'Build and test pipeline finished.'
        }
    }
}
